### ISSUE TITLE
Enable configuration of includes/excludes for yaml source files

### ISSUE THREAD

**Issue by ascheman** [jQAssistant/jqa-yaml2-plugin#10]
### Feature Description
 
I, as a _DevOps engineer_
would like to be able to analyze arbitrary YAML based sources,
e.g., to be able to reason about my _Ansible_ based provisioning.

### Additional information on the requested Feature

Therefore I propose to enhance the YAML 2 plugin with a property include for arbitrary file patterns (not only those ending with .yaml and .yml). It would then integrate with my [new jQA Ansible Plugin](https://github.com/ascheman/jqa-ansible-plugin/tree/main).

### How to Test

I will soon create a pull request with the desired feature and respective test cases.

### Definition of Done for the Implementers
- [x] We got a final feedback from the reporting user
- [x] Unittests have been written
- [ ] ~Integration tests have been written~
- [ ] ~Test coverage is the same or even better then before~
- [x] Documentation has been written 
- [x] Added a note on the new feature to the release notes

**Comment by obfischer** [comment]
Hi @ascheman, have you seen #6?

**Comment by ascheman** [comment]
Thanks, no, but you can close it as a duplicate of #10 and merge #11 to solve it 😇☺
-- 
Gerd Aschemann - mobil - +49 173 3264070


-------- Ursprüngliche Nachricht --------
Von: "Oliver B. Fischer" <notifications@github.com>
Gesendet: 7. März 2021 23:01:29 MEZ
An: jQAssistant/jqa-yaml2-plugin <jqa-yaml2-plugin@noreply.github.com>
CC: Gerd Aschemann <github@aschemann.net>, Mention <mention@noreply.github.com>
Betreff: Re: [jQAssistant/jqa-yaml2-plugin] Enable configuration of includes/excludes for yaml source files (#10)

Hi @ascheman, have you seen #6?
